### ISSUE TITLE
The shodan can't work

### ISSUE THREAD

**Issue by mosqudoo** [entynetproject/entropy#1]
like this

root@kali:~/entropy# entropy -b 2 -v --shodan PSKINdQe1GyxGgecYz2191H2JoS9qvgD
[!] Failed to install some necessary dependencies!
[!] Because of this Entropy will be work incorrectly!
[!] You can install dependencies from requirements.txt!

              __                        
  ___  ____  / /__________  ____  __  __    ___
 / _ \/ __ \/ __/ ___/ __ \/ __ \/ / / /  [|   |=|{)__
/  __/ / / / /_/ /  / /_/ / /_/ / /_/ /    |___| \/   )
\___/_/ /_/\__/_/   \____/ .___/\__, /      /|\      /|
                        /_/    /____/      / | \     | \

The error occured: name 'shodan' is not defined
Please use python3 entropy.py -h or entropy -h for more help.

**Comment by enty8080** [comment]
Do you have shodan installed?

**Comment by enty8080** [comment]
And what architecture you selected in the installer?

**Comment by enty8080** [comment]
Execute this commands: 
root@kali:~# cd ~/entropy && pip3 install -r requirements.txt
