### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by mehedi1194** [entynetproject/entropy#2]
When i lunch the main file it giving me this error 

Bu2ri7orzLchbn1qN"
  File "entropy", line 87
    if os.path.exists(outputfile):
                                             ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by enty8080** [comment]
I fixed this error. Sorry for this

**Comment by enty8080** [comment]
Re-install, or execute `entropy --update`
If not work:
`./uninstall.sh`
re-clone
`./install.sh`
