### ISSUE TITLE
Feature Request - Query for shodan

### ISSUE THREAD

**Issue by pispuso** [entynetproject/entropy#5]
Hello! Amazing project, thanks for it!

It would be nice to be able to query for specific countries for example while using shodan or zoomeye. I would love to filter as many results as possible.

Thanks!

**Comment by enty8080** [comment]
This is a very good idea, but there is a problem with the Shodan API key due to which the Shodan python library cannot filter webcams by country for ordinary users, only for those who have a paid plan.

**Comment by pispuso** [comment]
That's true, there is a limitation with the free user API in shodan. Other way to circumvent this could be add an option to load hosts from a file. This way a free shodan user could search using filters on the web and manually add the hosts to a list that can be loaded.

Anyway, just an idea.
